### ISSUE TITLE
[packet/generator] Segmentation Fault when stopping a non-started generator

### ISSUE THREAD

**Issue by ronanjs** [Spirent/openperf#354]
Following code (based on openperf-alpha) will crash OpenPerf:

```
async function run (genServerIP, genPortID) {

    const genClient = new OpenPerfClient(genServerIP)
    await genClient.check()

    const genPort = await genClient.ports().get(genPortID)
    const generators = genPort.generators()

    const gen = await generators.create('generator-01')
    if (!gen) return

    await gen.start()
    await wait(100)
    await gen.stop()
    await wait(100)
    await gen.delete()
}
```

Stack, when the crash is happening, is:

```
(gdb) bt
#0  stop () at /root/project/src/modules/packet/generator/source.cpp:221
#1  handle_request () at /root/project/src/modules/packet/generator/server.cpp:447
#2  0x0000000001129f99 in operator()<openperf::packet::generator::api::request_stop_generator>
    () at /root/project/src/modules/packet/generator/server.cpp:159
#3  __invoke_impl<std::variant<openperf::packet::generator::api::reply_generators, openperf::packet::generator::api::reply_generator_results, openperf::packet::generator::api::reply_tx_flows, openperf::packet::generator::api::reply_ok, openperf::packet::generator::api::reply_error>, (lambda at /root/project/src/modules/packet/generator/server.cpp:158:32) &, openperf::packet::generator::api::request_stop_generator &> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:60
#4  __invoke<(lambda at /root/project/src/modules/packet/generator/server.cpp:158:32) &, openperf::packet::generator::api::request_stop_generator &> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95
#5  __visit_invoke ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/variant:830
#6  0x00000000011259ff in visit<(lambda at /root/project/src/modules/packet/generator/server.cpp:158:32) &, std::variant<openperf::packet::generator::api::request_list_generators, openperf::packet::generator::api::request_create_generator, openperf::packet::generator::api::request_delete_generators, openperf::packet::generator::api::request_get_generator, openperf::packet::generator::api::request_delete_generator, openperf::packet::generator::api::request_start_generator, openperf::packet::generator::api::request_stop_generator, openperf::packet::generator::api::request_bulk_create_generators, openperf::packet::generator::api::request_bulk_delete_generators, openperf::packet::generator::api::request_bulk_start_generators, openperf::packet::generator::api::request_bulk_stop_generators, openperf::packet::generator::api::request_toggle_generator, openperf::packet::generator::api::request_list_generator_results, openperf::packet::generator::api::request_delete_generator_results, openperf::packet::generator::api::request_get_generator_result, openperf::packet::generator::api::request_delete_generator_result, openperf::packet::generator::api::request_list_tx_flows, openperf::packet::generator::api::request_get_tx_flow> &> () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/variant:1386
#7  handle_rpc_request () at /root/project/src/modules/packet/generator/server.cpp:161
#8  0x0000000000f1b2b2 in _do_event_handling ()
    at /root/project/src/framework/core/op_event_loop_epoll.c:519
#9  0x0000000000f1b6c6 in op_event_loop_run_timeout ()
    at /root/project/src/framework/core/op_event_loop_epoll.c:656
#10 0x0000000001125868 in op_event_loop_run
_forever ()
    at /root/project/src/framework/core/op_event_loop_epoll.c:680
#11 run () at /root/project/src/framework/core/op_event_loop.hpp:20
```

**Comment by ronanjs** [comment]
This issue can be reproduced by just sending a stop command to a generator which is not started....
