### ISSUE TITLE
[analyser] Assertion `kind() == kind_t::inner' failed in immer/detail/hamts/node.hpp

### ISSUE THREAD

**Issue by ronanjs** [Spirent/openperf#362]
This error seems to be a concurrency issue between the Rest API "flow iteration" and the flow analyzer.
It can be reproduced only when using a NAT between the two host - but the NAT should just be a side cause affecting the traffic pattern - which should be the real root cause.  

```
(gdb) info frame
Stack level 3, frame at 0x7fff867f87f0:
 rip = 0xf82761
    in immer::detail::hamts::node<std::pair<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters>, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::values() (/root/project/deps/immer/immer/detail/hamts/node.hpp:121); saved rip = 0xf853ac
 called by frame at 0x7fff867f8810, caller of frame at 0x7fff867f87e0
 source language c++.
 Arglist at 0x7fff867f87d8, args:
 Locals at 0x7fff867f87d8, Previous frame's sp is 0x7fff867f87f0
 Saved registers:
  rip at 0x7fff867f87e8
```

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c50535 in __GI_abort () at abort.c:79
#2  0x00007ffff7c5040f in __assert_fail_base (fmt=0x7ffff7db2ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x6538f3 <.str.9.llvm> "kind() == kind_t::inner",
    file=0x77e2a1 <.str.5.llvm> "/root/project/deps/immer/immer/detail/hamts/node.hpp", line=153, function=<optimized out>) at assert.c:92
#3  0x00007ffff7c5e102 in __GI___assert_fail (assertion=0x6538f3 <.str.9.llvm> "kind() == kind_t::inner",
    file=0x77e2a1 <.str.5.llvm> "/root/project/deps/immer/immer/detail/hamts/node.hpp", line=153,
    function=0x6e2772 "auto immer::detail::hamts::node<std::pair<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters>, immer::map<std::pair<unsigned int, std:"...) at assert.c:101
#4  0x0000000000f825f2 in nodemap () at /root/project/deps/immer/immer/detail/hamts/node.hpp:153
#5  step_down () at /root/project/deps/immer/immer/detail/hamts/champ_iterator.hpp:81
#6  0x0000000000f824fb in immer::detail::hamts::champ_iterator<std::pair<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters>, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::ensure_valid_() ()
    at /root/project/deps/immer/immer/detail/hamts/champ_iterator.hpp:128
#7  0x0000000000f8715e in increment () at /root/project/deps/immer/immer/detail/hamts/champ_iterator.hpp:74
#8  increment<immer::detail::hamts::champ_iterator<std::pair<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters>, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>::hash_key, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>&> () at /root/project/deps/immer/immer/detail/iterator_facade.hpp:26
#9  operator++ () at /root/project/deps/immer/immer/detail/iterator_facade.hpp:121
#10 for_each<immer::detail::hamts::champ_iterator<std::pair<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters>, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>::hash_key, immer::map<std::pair<unsigned int, std::optional<unsigned int> >, openperf::packet::analyzer::statistics::generic_flow_counters, std::hash<std::pair<unsigned int, std::optional<unsigned int> > >, std::equal_to<std::pair<unsigned int, std::optional<unsigned int> > >, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5>, (lambda at /root/project/src/modules/packet/analyzer/sink_transmogrify.cpp:222:13)> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:3881
#11 operator()<std::pair<openperf::utils::recycle::depot<1>, openperf::packet::analyzer::statistics::flow::counter_map<openperf::packet::analyzer::statistics::generic_flow_counters> > > () at /root/project/src/modules/packet/analyzer/sink_transmogrify.cpp:219
#12 for_each<__gnu_cxx::__normal_iterator<const std::pair<openperf::utils::recycle::depot<1>, openperf::packet::analyzer::statistics::flow::counter_map<openperf::packet::analyzer::statistics::generic_flow_counters> > *, std::vector<std::pair<openperf::utils::recycle::depot<1>, openperf::packet::analyzer::statistics::flow::counter_map<openperf::packet::analyzer::statistics::generic_flow_counters> >, std::allocator<std::pair<openperf::utils::recycle::depot<1>, openperf::packet::analyzer::statistics::flow::counter_map<openperf::packet::analyzer::statistics::generic_flow_counters> > > > >, (lambda at /root/project/src/modules/packet/analyzer/sink_transmogrify.cpp:217:51)> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:3882
#13 to_swagger () at /root/project/src/modules/packet/analyzer/sink_transmogrify.cpp:217
#14 to_swagger () at /root/project/src/modules/packet/analyzer/sink_transmogrify.cpp:495
#15 0x0000000000f7eb20 in handle_request () at /root/project/src/modules/packet/analyzer/server.cpp:625
#16 0x0000000000f80157 in operator()<openperf::packet::analyzer::api::request_get_analyzer_result> ()
    at /root/project/src/modules/packet/analyzer/server.cpp:171
#17 __invoke_impl<std::variant<openperf::packet::analyzer::api::reply_analyzers, openperf::packet::analyzer::api::reply_analyzer_results, openperf::packet::analyzer::api::reply_rx_flows, openperf::packet::analyzer::api::reply_ok, openperf::packet::analyzer::api::reply_error>, (lambda at /root/project/src/modules/packet/analyzer/server.cpp:170:32) &, openperf::packet::analyzer::api::request_get_analyzer_result &> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:60
#18 __invoke<(lambda at /root/project/src/modules/packet/analyzer/server.cpp:170:32) &, openperf::packet::analyzer::api::request_get_analyzer_result &> () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95
#19 __visit_invoke () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/variant:830
#20 0x0000000000f7be97 in visit<(lambda at /root/project/src/modules/packet/analyzer/server.cpp:170:32) &, std::variant<openperf::packet::analyzer::api::request_list_analyzers, openperf::packet::analyzer::api::request_create_analyzer, openperf::packet::analyzer::api::request_delete_analyzers, openperf::packet::analyzer::api::request_get_analyzer, openperf::packet::analyzer::api::request_delete_analyzer, openperf::packet::analyzer::api::request_reset_analyzer, openperf::packet::analyzer::api::request_start_analyzer, openperf::packet::analyzer::api::request_stop_analyzer, openperf::packet::analyzer::api::request_bulk_create_analyzers, openperf::packet::analyzer::api::request_bulk_delete_analyzers, openperf::packet::analyzer::api::request_bulk_start_analyzers, openperf::packet::analyzer::api::request_bulk_stop_analyzers, openperf::packet::analyzer::api::request_list_analyzer_results, openperf::packet::analyzer::api::request_delete_analyzer_results, openperf::packet::analyzer::api::request_get_analyzer_result, openperf::packet::analyzer::api::request_delete_analyzer_result, openperf::packet::analyzer::api::request_list_rx_flows, openperf::packet::analyzer::api::request_get_rx_flow> &> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/variant:1386
#21 handle_rpc_request () at /root/project/src/modules/packet/analyzer/server.cpp:173
#22 0x0000000000f20476 in _do_event_handling () at /root/project/src/framework/core/op_event_loop_epoll.c:519
#23 0x0000000000f20887 in op_event_loop_run_timeout () at /root/project/src/framework/core/op_event_loop_epoll.c:656
#24 0x0000000000f7b5e6 in op_event_loop_run_forever () at /root/project/src/framework/core/op_event_loop_epoll.c:680
#25 run () at /root/project/src/framework/core/op_event_loop.hpp:20
#26 operator() () at /root/project/src/modules/packet/analyzer/init.cpp:49
#27 __invoke_impl<void, (lambda at /root/project/src/modules/packet/analyzer/init.cpp:43:33)> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:60
--Type <RET> for more, q to quit, c to continue without paging--
#28 __invoke<(lambda at /root/project/src/modules/packet/analyzer/init.cpp:43:33)> ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95
#29 _M_invoke<0> () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:244
#30 operator() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:253
#31 _M_run () at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:196
#32 0x0000000000de679f in execute_native_thread_routine ()
#33 0x00007ffff7df8fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#34 0x00007ffff7d274cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
````

**Comment by ronanjs** [comment]
Those are the frames received just before the crash:

```
13:26:48.450827  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 017d 0000 0000  .=$.P..P.*.}....
	0x0020:  0000 0000 0000 0000 0000 ff2f 4b1b b628  .........../K..(
	0x0030:  be95 46b1 82d0 aac0 4643 6479 0000       ..F.....FCdy..

13:26:48.550812  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 7357 0000 0000  .=$.P..P.*sW....
	0x0020:  0000 0000 0000 0000 0000 fe5e 9537 6e51  ...........^.7nQ
	0x0030:  7c2a 8d63 0538 fd41 d212 8c2b 0000       |*.c.8.A...+..
13:26:48.650835  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a eaa3 0000 0000  .=$.P..P.*......
	0x0020:  0000 0000 0000 0000 0000 fdcc f742 06db  .............B..
	0x0030:  3bea d114 8d10 06d0 dde0 7a36 0000       ;.........z6..
13:26:48.750826  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a e240 0000 0000  .=$.P..P.*.@....
	0x0020:  0000 0000 0000 0000 0000 fcbd 296e dea2  ............)n..
	0x0030:  f955 1ac6 0afe 6dab 37b1 33ff 0000       .U....m.7.3...
13:26:48.850826  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a ce27 0000 0000  .=$.P..P.*.'....
	0x0020:  0000 0000 0000 0000 0000 fb99 ed84 0fb6  ................
	0x0030:  76d5 a229 1b94 f32c 9c54 5474 0000       v..)...,.TTt..
13:26:48.950822  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a d9d5 0000 0000  .=$.P..P.*......
	0x0020:  0000 0000 0000 0000 0000 fae8 33a8 d7cf  ............3...
	0x0030:  b46a 69fb 9c7b 6147 4605 9d20 0000       .ji..{aGF.....
13:26:49.050823  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 5855 0000 0000  .=$.P..P.*XU....
	0x0020:  0000 0000 0000 0000 0000 f97a 51dd bf45  ...........zQ..E
	0x0030:  f3aa 358c 1440 dddd 9ef7 c245 0000       ..5..@.....E..
13:26:49.150825  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 95b4 0000 0000  .=$.P..P.*......
	0x0020:  0000 0000 0000 0000 0000 f80b 8ff1 673c  ..............g<
	0x0030:  3115 fe5e 93ab c653 53a6 7d7d 0000       1..^...SS.}}..
13:26:49.250823  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 5014 0000 0000  .=$.P..P.*P.....
	0x0020:  0000 0000 0000 0000 0000 f733 d808 1d6c  ...........3...l
	0x0030:  ecab 4452 369d efe4 993c b20b 0000       ..DR6....<....
13:26:49.350837  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 39e8 0000 0000  .=$.P..P.*9.....
	0x0020:  0000 0000 0000 0000 0000 f642 0624 c515  ...........B.$..
	0x0030:  2e14 8f80 b14e 78df a06d 5bf0 0000       .....Nx..m[...
13:26:49.450840  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a f0b5 0000 0000  .=$.P..P.*......
	0x0020:  0000 0000 0000 0000 0000 f5d0 6451 ad9f  ............dQ..
	0x0030:  69d4 d3f7 397a d912 bb9f db14 0000       i...9z........
13:26:49.550837  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 196b 0000 0000  .=$.P..P.*.k....
	0x0020:  0000 0000 0000 0000 0000 f4a1 ba7d 75e6  .............}u.
	0x0030:  ab6b 1825 be92 cea4 55ce fa7d 0000       .k.%....U..}..
13:26:49.650838  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a cd68 0000 0000  .=$.P..P.*.h....
	0x0020:  0000 0000 0000 0000 0000 f385 7e97 a4f2  ............~...
	0x0030:  24eb a0ca aff0 54ee 0e2b 224d 0000       $.....T..+"M..
13:26:49.750837  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 57e1 0000 0000  .=$.P..P.*W.....
	0x0020:  0000 0000 0000 0000 0000 f2f4 a0bb 7c8b  ..............|.
	0x0030:  e654 6b18 281f cce0 557a db80 0000       .Tk.(...Uz....
13:26:49.850839  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 3334 0000 0000  .=$.P..P.*34....
	0x0020:  0000 0000 0000 0000 0000 f166 c2ce 1401  ...........f....
	0x0030:  a194 376f a02e 70f4 d988 206b 0000       ..7o..p....k..
13:26:49.950838  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a 9633 0000 0000  .=$.P..P.*.3....
	0x0020:  0000 0000 0000 0000 0000 f017 1ce2 cc78  ...............x
	0x0030:  632b fcbd 27c1 638f ebd9 98cb 0000       c+..'.c.......
13:26:50.050828  In 00:00:02:4b:b8:15 ethertype IPv4 (0x0800), length 78: 192.168.224.253.20483 > 10.61.36.222.80: UDP, length 34
	0x0000:  4500 003e 0000 0000 3d11 acee c0a8 e0fd  E..>....=.......
	0x0010:  0a3d 24de 5003 0050 002a d22f 0000 0000  .=$.P..P.*./....
	0x0020:  0000 0000 0000 0000 0000 ef16 6d3c e0a0  ............m<..
	0x0030:  1ae9 4376 ea5a 2d86 97bc c264 0000       ..Cv.Z-....d..
```
